package recomendacionpelicula;

public class Catalogo extends javax.swing.JFrame {
    private java.util.List<Pelicula> catalogo = new java.util.ArrayList<>();

private void cargarCatalogo() {
    catalogo.add(new Pelicula(1,  "Mad Max: Fury Road",       "Accion",          2015, 8.1, "R"));
    catalogo.add(new Pelicula(2,  "The Dark Knight",          "Accion",          2008, 9.0, "PG-13"));
    catalogo.add(new Pelicula(3,  "Top Gun: Maverick",        "Accion",          2022, 8.3, "PG-13"));
    catalogo.add(new Pelicula(4,  "John Wick",                "Accion",          2014, 7.4, "R"));
    catalogo.add(new Pelicula(5,  "Superbad",                 "Comedia",         2007, 7.6, "R"));
    catalogo.add(new Pelicula(6,  "Knives Out",               "Comedia",         2019, 7.9, "PG-13"));
    catalogo.add(new Pelicula(7,  "Paddington 2",             "Comedia",         2017, 7.8, "PG"));
    catalogo.add(new Pelicula(8,  "Shawshank Redemption",     "Drama",           1994, 9.3, "R"));
    catalogo.add(new Pelicula(9,  "Parasite",                 "Drama",           2019, 8.5, "R"));
    catalogo.add(new Pelicula(10, "Marriage Story",           "Drama",           2019, 7.9, "R"));
    catalogo.add(new Pelicula(11, "Hereditary",               "Terror",          2018, 7.3, "R"));
    catalogo.add(new Pelicula(12, "Get Out",                  "Terror",          2017, 7.7, "R"));
    catalogo.add(new Pelicula(13, "A Quiet Place",            "Terror",          2018, 7.5, "PG-13"));
    catalogo.add(new Pelicula(14, "Interstellar",             "Ciencia Ficcion", 2014, 8.7, "PG-13"));
    catalogo.add(new Pelicula(15, "Arrival",                  "Ciencia Ficcion", 2016, 7.9, "PG-13"));
    catalogo.add(new Pelicula(16, "Spirited Away",            "Animacion",       2001, 8.6, "PG"));
    catalogo.add(new Pelicula(17, "Coco",                     "Animacion",       2017, 8.4, "PG"));
    catalogo.add(new Pelicula(18, "Spider-Man Spider-Verse",  "Animacion",       2018, 8.4, "PG"));
    catalogo.add(new Pelicula(19, "WALL-E",                   "Animacion",       2008, 8.4, "G"));
    catalogo.add(new Pelicula(20, "La La Land",               "Romance",         2016, 8.0, "PG-13"));
    catalogo.add(new Pelicula(21, "Eternal Sunshine",         "Romance",         2004, 8.3, "R"));
    catalogo.add(new Pelicula(22, "Planet Earth II",          "Documental",      2016, 9.5, "G"));
    catalogo.add(new Pelicula(23, "Free Solo",                "Documental",      2018, 8.2, "PG-13"));
    catalogo.add(new Pelicula(24, "13th",                     "Documental",      2016, 8.2, "PG-13"));
}

// Muestra las películas del género en jPanel3
private void mostrarGenero(String genero) {
    jPanel3.removeAll();
    jPanel3.setBackground(new java.awt.Color(27,25,25));
    jPanel3.setLayout(new java.awt.BorderLayout());

    javax.swing.JTextArea area = new javax.swing.JTextArea();
    area.setEditable(false);
    area.setBackground(new java.awt.Color(40,38,38));
    area.setForeground(java.awt.Color.WHITE);
    area.setFont(new java.awt.Font("Segoe UI", 0, 13));
    area.setMargin(new java.awt.Insets(10,10,10,10));

    StringBuilder sb = new StringBuilder();
    sb.append("══ ").append(genero.toUpperCase()).append(" ══\n\n");
    int n = 1;
    for (Pelicula p : catalogo) {
        if (p.getGenero().equalsIgnoreCase(genero)) {
            sb.append(n++).append(". ").append(p.toResumen()).append("\n");
        }
    }
    if (n == 1) sb.append("No hay películas en este género.");
    area.setText(sb.toString());

    jPanel3.add(new javax.swing.JScrollPane(area), java.awt.BorderLayout.CENTER);
    jPanel3.revalidate();
    jPanel3.repaint();
}
    public Catalogo() {
        initComponents();
        cargarCatalogo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnDrama = new javax.swing.JButton();
        btnCienciaFiccion = new javax.swing.JButton();
        btnRomance = new javax.swing.JButton();
        btnComedia = new javax.swing.JButton();
        btnAnimacion = new javax.swing.JButton();
        btnAccion = new javax.swing.JButton();
        btnDocumentacion = new javax.swing.JButton();
        btnTerror = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RECOMENDACIONES");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(27, 25, 25));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDrama.setBackground(new java.awt.Color(204, 0, 0));
        btnDrama.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnDrama.setForeground(new java.awt.Color(255, 255, 255));
        btnDrama.setText("Drama");
        btnDrama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDramaActionPerformed(evt);
            }
        });
        jPanel2.add(btnDrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 50));

        btnCienciaFiccion.setBackground(new java.awt.Color(204, 0, 0));
        btnCienciaFiccion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCienciaFiccion.setForeground(new java.awt.Color(255, 255, 255));
        btnCienciaFiccion.setText("Ciencia Ficcion");
        btnCienciaFiccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCienciaFiccionActionPerformed(evt);
            }
        });
        jPanel2.add(btnCienciaFiccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 50));

        btnRomance.setBackground(new java.awt.Color(204, 0, 0));
        btnRomance.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRomance.setForeground(new java.awt.Color(255, 255, 255));
        btnRomance.setText("Romance");
        btnRomance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRomanceActionPerformed(evt);
            }
        });
        jPanel2.add(btnRomance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, 50));

        btnComedia.setBackground(new java.awt.Color(204, 0, 0));
        btnComedia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnComedia.setForeground(new java.awt.Color(255, 255, 255));
        btnComedia.setText("Comedia");
        btnComedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComediaActionPerformed(evt);
            }
        });
        jPanel2.add(btnComedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 50));

        btnAnimacion.setBackground(new java.awt.Color(204, 0, 0));
        btnAnimacion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAnimacion.setForeground(new java.awt.Color(255, 255, 255));
        btnAnimacion.setText("Animacion");
        btnAnimacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnimacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnAnimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 150, 50));

        btnAccion.setBackground(new java.awt.Color(204, 0, 0));
        btnAccion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAccion.setForeground(new java.awt.Color(255, 255, 255));
        btnAccion.setText("Acción");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });
        jPanel2.add(btnAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        btnDocumentacion.setBackground(new java.awt.Color(204, 0, 0));
        btnDocumentacion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnDocumentacion.setForeground(new java.awt.Color(255, 255, 255));
        btnDocumentacion.setText("Documentacion");
        btnDocumentacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocumentacionActionPerformed(evt);
            }
        });
        jPanel2.add(btnDocumentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 150, 50));

        btnTerror.setBackground(new java.awt.Color(204, 0, 0));
        btnTerror.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnTerror.setForeground(new java.awt.Color(255, 255, 255));
        btnTerror.setText("Terror");
        btnTerror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerrorActionPerformed(evt);
            }
        });
        jPanel2.add(btnTerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 620, 480));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        mostrarGenero("Accion");
    }//GEN-LAST:event_btnAccionActionPerformed

    private void btnDramaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDramaActionPerformed
        mostrarGenero("Drama");
    }//GEN-LAST:event_btnDramaActionPerformed

    private void btnCienciaFiccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCienciaFiccionActionPerformed
        mostrarGenero("Ciencia Ficcion");
    }//GEN-LAST:event_btnCienciaFiccionActionPerformed

    private void btnRomanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRomanceActionPerformed
        mostrarGenero("Romance");
    }//GEN-LAST:event_btnRomanceActionPerformed

    private void btnComediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComediaActionPerformed
       mostrarGenero("Comedia");
    }//GEN-LAST:event_btnComediaActionPerformed

    private void btnTerrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerrorActionPerformed
        mostrarGenero("Terror");
    }//GEN-LAST:event_btnTerrorActionPerformed

    private void btnAnimacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnimacionActionPerformed
        mostrarGenero("Animacion");
    }//GEN-LAST:event_btnAnimacionActionPerformed

    private void btnDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocumentacionActionPerformed
        mostrarGenero("Documental");
    }//GEN-LAST:event_btnDocumentacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnAnimacion;
    private javax.swing.JButton btnCienciaFiccion;
    private javax.swing.JButton btnComedia;
    private javax.swing.JButton btnDocumentacion;
    private javax.swing.JButton btnDrama;
    private javax.swing.JButton btnRomance;
    private javax.swing.JButton btnTerror;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
