/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recomendacionpelicula;

/**
 *
 * @author JUDITH
 */
public class Catalogo extends javax.swing.JFrame {

    /**
     * Creates new form Catalogo
     */
    public Catalogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnDrama = new javax.swing.JButton();
        btnCienciaFiccion = new javax.swing.JButton();
        btnRomance = new javax.swing.JButton();
        btnComedia = new javax.swing.JButton();
        btnAnimacion = new javax.swing.JButton();
        btnAccion = new javax.swing.JButton();
        btnDocumentacion = new javax.swing.JButton();
        btnTerror = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RECOMENDACIONES");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 100, -1, -1));

        jPanel2.setBackground(new java.awt.Color(27, 25, 25));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDrama.setBackground(new java.awt.Color(204, 0, 0));
        btnDrama.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnDrama.setForeground(new java.awt.Color(255, 255, 255));
        btnDrama.setText("Drama");
        jPanel2.add(btnDrama, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 50));

        btnCienciaFiccion.setBackground(new java.awt.Color(204, 0, 0));
        btnCienciaFiccion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnCienciaFiccion.setForeground(new java.awt.Color(255, 255, 255));
        btnCienciaFiccion.setText("Ciencia Ficcion");
        jPanel2.add(btnCienciaFiccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 150, 50));

        btnRomance.setBackground(new java.awt.Color(204, 0, 0));
        btnRomance.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnRomance.setForeground(new java.awt.Color(255, 255, 255));
        btnRomance.setText("Romance");
        jPanel2.add(btnRomance, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 150, 50));

        btnComedia.setBackground(new java.awt.Color(204, 0, 0));
        btnComedia.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnComedia.setForeground(new java.awt.Color(255, 255, 255));
        btnComedia.setText("Comedia");
        jPanel2.add(btnComedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 150, 50));

        btnAnimacion.setBackground(new java.awt.Color(204, 0, 0));
        btnAnimacion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAnimacion.setForeground(new java.awt.Color(255, 255, 255));
        btnAnimacion.setText("Animacion");
        jPanel2.add(btnAnimacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 150, 50));

        btnAccion.setBackground(new java.awt.Color(204, 0, 0));
        btnAccion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnAccion.setForeground(new java.awt.Color(255, 255, 255));
        btnAccion.setText("Acción");
        jPanel2.add(btnAccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 150, 50));

        btnDocumentacion.setBackground(new java.awt.Color(204, 0, 0));
        btnDocumentacion.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnDocumentacion.setForeground(new java.awt.Color(255, 255, 255));
        btnDocumentacion.setText("Documentacion");
        jPanel2.add(btnDocumentacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 150, 50));

        btnTerror.setBackground(new java.awt.Color(204, 0, 0));
        btnTerror.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnTerror.setForeground(new java.awt.Color(255, 255, 255));
        btnTerror.setText("Terror");
        jPanel2.add(btnTerror, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 50));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 620, 480));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Catalogo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Catalogo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnAnimacion;
    private javax.swing.JButton btnCienciaFiccion;
    private javax.swing.JButton btnComedia;
    private javax.swing.JButton btnDocumentacion;
    private javax.swing.JButton btnDrama;
    private javax.swing.JButton btnRomance;
    private javax.swing.JButton btnTerror;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
