package recomendacionpelicula;

public class Estadistica extends javax.swing.JFrame {

private ArbolBST arbol = new ArbolBST();
private int idContador = 100;

// Cargar películas base en el árbol
private void cargarArbolInicial() {
    arbol.insertar(new Pelicula(1,  "The Dark Knight",      "Accion",    2008, 9.0, "PG-13"));
    arbol.insertar(new Pelicula(2,  "Spirited Away",        "Animacion", 2001, 8.6, "PG"));
    arbol.insertar(new Pelicula(3,  "Interstellar",         "Sci-Fi",    2014, 8.7, "PG-13"));
    arbol.insertar(new Pelicula(4,  "Shawshank Redemption", "Drama",     1994, 9.3, "R"));
    arbol.insertar(new Pelicula(5,  "Parasite",             "Drama",     2019, 8.5, "R"));
    arbol.insertar(new Pelicula(6,  "Top Gun: Maverick",    "Accion",    2022, 8.3, "PG-13"));
    arbol.insertar(new Pelicula(7,  "John Wick",            "Accion",    2014, 7.4, "R"));
    dibujarArbol();
    mostrarRecorrido("IN");
}
    public Estadistica() {
        initComponents();
    cargarArbolInicial();
}
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnLimpiar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtrecorrido = new javax.swing.JTextField();
        btnInsertar1 = new javax.swing.JButton();
        btnInsertar3 = new javax.swing.JButton();
        btnInsertar4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnInsertar2 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(27, 25, 25));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLimpiar.setBackground(new java.awt.Color(204, 0, 0));
        btnLimpiar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 790, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Genero");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 160, -1));
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 380, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 790, 250));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(txtrecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 770, 30));

        btnInsertar1.setBackground(new java.awt.Color(204, 0, 0));
        btnInsertar1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnInsertar1.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar1.setText("PreOrden");
        btnInsertar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnInsertar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 120, 20));

        btnInsertar3.setBackground(new java.awt.Color(204, 0, 0));
        btnInsertar3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnInsertar3.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar3.setText("PosOrden");
        btnInsertar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar3ActionPerformed(evt);
            }
        });
        jPanel3.add(btnInsertar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 20));

        btnInsertar4.setBackground(new java.awt.Color(204, 0, 0));
        btnInsertar4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnInsertar4.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar4.setText("InOrden");
        btnInsertar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar4ActionPerformed(evt);
            }
        });
        jPanel3.add(btnInsertar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 120, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 790, 80));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Insertar pelicula");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Insertar pelicula");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ttulo ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        btnInsertar2.setBackground(new java.awt.Color(204, 0, 0));
        btnInsertar2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnInsertar2.setForeground(new java.awt.Color(255, 255, 255));
        btnInsertar2.setText("Insertar");
        btnInsertar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertar2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnInsertar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 150, 30));

        btnEliminar.setBackground(new java.awt.Color(204, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, 150, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnInsertar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar2ActionPerformed
        String titulo = jTextField2.getText().trim();
String genero = jTextField1.getText().trim();
if (titulo.isEmpty() || genero.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Completa Título y Género.", "Campos requeridos", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}
// Rating aleatorio entre 6.0 y 9.5 para demo
double rating = 6.0 + Math.round(Math.random() * 35) / 10.0;
Pelicula nueva = new Pelicula(++idContador, titulo, genero, 2024, rating, "PG-13");
arbol.insertar(nueva);
dibujarArbol();
mostrarRecorrido("IN");
jTextField2.setText("");
jTextField1.setText("");
javax.swing.JOptionPane.showMessageDialog(this, "\"" + titulo + "\" insertada con rating " + rating, "Insertada", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnInsertar2ActionPerformed

    private void btnInsertar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar4ActionPerformed
        mostrarRecorrido("IN");
    }//GEN-LAST:event_btnInsertar4ActionPerformed

    private void btnInsertar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar1ActionPerformed
        mostrarRecorrido("PRE");
    }//GEN-LAST:event_btnInsertar1ActionPerformed

    private void btnInsertar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertar3ActionPerformed
        mostrarRecorrido("POST");
    }//GEN-LAST:event_btnInsertar3ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String titulo = jTextField2.getText().trim();
if (titulo.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Escribe el título a eliminar en el campo Título.", "Campo requerido", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}
Pelicula encontrada = arbol.buscarPorTitulo(titulo);
if (encontrada == null) {
    javax.swing.JOptionPane.showMessageDialog(this, "No se encontró: " + titulo, "No encontrado", javax.swing.JOptionPane.WARNING_MESSAGE);
} else {
    javax.swing.JOptionPane.showMessageDialog(this, "Eliminación visual completada para: " + titulo + "\n(En BST la eliminación se refleja en el recorrido)", "Eliminado", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    jTextField2.setText("");
}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        arbol = new ArbolBST();
cargarArbolInicial();
jTextField2.setText("");
jTextField1.setText("");
txtrecorrido.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed
// Muestra el recorrido en txtrecorrido
private void mostrarRecorrido(String tipo) {
    java.util.List<Pelicula> lista;
    String label;
    switch (tipo) {
        case "PRE":  lista = arbol.preorden();   label = "PREORDEN: ";  break;
        case "POST": lista = arbol.postorden();  label = "POSTORDEN: "; break;
        default:     lista = arbol.inorden();    label = "INORDEN: ";   break;
    }
    StringBuilder sb = new StringBuilder(label);
    for (int i = 0; i < lista.size(); i++) {
        sb.append(lista.get(i).getTitulo()).append(" (").append(lista.get(i).getRating()).append(")");
        if (i < lista.size()-1) sb.append(" → ");
    }
    txtrecorrido.setText(sb.toString());
}

// Dibuja el árbol en jPanel1 usando Canvas
private void dibujarArbol() {
    jPanel1.removeAll();
    jPanel1.setBackground(new java.awt.Color(27,25,25));
    jPanel1.setLayout(null);

    // Panel de dibujo personalizado
    javax.swing.JPanel canvas = new javax.swing.JPanel() {
        @Override
        protected void paintComponent(java.awt.Graphics g) {
            super.paintComponent(g);
            setBackground(new java.awt.Color(27,25,25));
            if (!arbol.estaVacio()) {
                dibujarNodo(g, arbol.getRaiz(), getWidth()/2, 30, getWidth()/4);
            } else {
                g.setColor(java.awt.Color.WHITE);
                g.drawString("Árbol vacío", getWidth()/2 - 40, getHeight()/2);
            }
        }
        private void dibujarNodo(java.awt.Graphics g, Nodo nodo, int x, int y, int offset) {
            if (nodo == null) return;
            // Dibujar líneas a hijos
            g.setColor(new java.awt.Color(200,200,200));
            if (nodo.izquierdo != null) {
                g.drawLine(x, y+18, x-offset, y+60);
                dibujarNodo(g, nodo.izquierdo, x-offset, y+60, offset/2);
            }
            if (nodo.derecho != null) {
                g.drawLine(x, y+18, x+offset, y+60);
                dibujarNodo(g, nodo.derecho, x+offset, y+60, offset/2);
            }
            // Dibujar círculo del nodo
            g.setColor(new java.awt.Color(204,0,0));
            g.fillOval(x-22, y-10, 44, 36);
            g.setColor(java.awt.Color.WHITE);
            g.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 10));
            String rating = String.valueOf(nodo.pelicula.getRating());
            g.drawString(rating, x - g.getFontMetrics().stringWidth(rating)/2, y+12);
            // Título corto debajo
            g.setColor(new java.awt.Color(180,180,180));
            g.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 9));
            String corto = nodo.pelicula.getTitulo().length()>10 ? nodo.pelicula.getTitulo().substring(0,10)+"…" : nodo.pelicula.getTitulo();
            g.drawString(corto, x - g.getFontMetrics().stringWidth(corto)/2, y+32);
        }
    };
    canvas.setBounds(0, 0, 790, 250);
    jPanel1.add(canvas);
    jPanel1.revalidate();
    jPanel1.repaint();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (ClassNotFoundException ex) {
    java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (InstantiationException ex) {
    java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (IllegalAccessException ex) {
    java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
} catch (javax.swing.UnsupportedLookAndFeelException ex) {
    java.util.logging.Logger.getLogger(Estadistica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estadistica().setVisible(true);


            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnInsertar1;
    private javax.swing.JButton btnInsertar2;
    private javax.swing.JButton btnInsertar3;
    private javax.swing.JButton btnInsertar4;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtrecorrido;
    // End of variables declaration//GEN-END:variables
}
